model:
    arch: vgg
data_set:
    name: voc
    path: '/content/drive/My Drive/ML/data/VOCdevkit/VOC2012'
data_loader:
    num_workers: 8
train:
    batch_size: 16
    epoch: 100
    lr: 1.0e-2
    momentum: 0.5
validate:
    batch_size: 1000
checkpoint:
    path: './checkpoints'
    prefix: 'sample'
log:
    interval: 10